#!/usr/bin/env python3
"""
Summarize construction battery results into compact CSV and LaTeX tables.

Inputs:
  - out/cx_battery_eval.csv
  - out/cx_battery_prevalence.csv
Outputs:
  - out/cx_battery_summary.csv
  - out/cx_battery_summary.tex
  - out/cx_battery_prevalence.tex
"""
from __future__ import annotations

import os
from typing import List, Dict

import pandas as pd

EVAL_PATH = os.path.join("out", "cx_battery_eval.csv")
PREV_PATH = os.path.join("out", "cx_battery_prevalence.csv")
OUT_SUMMARY = os.path.join("out", "cx_battery_summary.csv")
OUT_SUMMARY_TEX = os.path.join("out", "cx_battery_summary.tex")
OUT_PREV_TEX = os.path.join("out", "cx_battery_prevalence.tex")


def fmt_float(val: float) -> str:
    if pd.isna(val):
        return "--"
    return f"{val:.3f}"


def fmt_int(val: float) -> str:
    if pd.isna(val):
        return "--"
    return f"{int(val)}"


def latex_escape(text: str) -> str:
    return text.replace("_", "\\_")


def make_summary(eval_df: pd.DataFrame) -> pd.DataFrame:
    ok = eval_df[eval_df["status"] == "ok"].copy()
    rows: List[Dict[str, float]] = []
    for (construction, train, test), sub in ok.groupby(["construction", "train", "test"]):
        pivot = sub.set_index("model")
        if "full" not in pivot.index:
            continue
        full = float(pivot.loc["full", "pr_auc"])
        row: Dict[str, float] = {
            "construction": construction,
            "train": train,
            "test": test,
            "n_train": int(pivot.loc["full", "n_train"]),
            "pos_train": int(pivot.loc["full", "pos_train"]),
            "n_test": int(pivot.loc["full", "n_test"]),
            "pos_test": int(pivot.loc["full", "pos_test"]),
            "full_pr_auc": full,
        }
        for m in ["no_cue1", "no_cue2", "no_cue3"]:
            if m in pivot.index:
                row[f"{m}_pr_auc"] = float(pivot.loc[m, "pr_auc"])
                row[f"{m}_delta"] = float(full - pivot.loc[m, "pr_auc"])
            else:
                row[f"{m}_pr_auc"] = float("nan")
                row[f"{m}_delta"] = float("nan")
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["construction", "train", "test"])


def write_summary_tex(df: pd.DataFrame) -> None:
    lines = []
    lines.append("% Auto-generated by python/22_summarize_construction_battery.py")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\caption{Construction battery results for estimable train--test pairs. Cue ablations report the change in PR--AUC relative to the full model (positive values indicate drops).}")
    lines.append("  \\label{tab:cx-battery-results}")
    lines.append("  \\begin{tabular}{l l r r r r r r}")
    lines.append("    \\toprule")
    lines.append("    Construction & Direction & $n_{tr}$ & $n_{te}$ & PR--AUC & $\\Delta$C1 & $\\Delta$C2 & $\\Delta$C3 \\\\")
    lines.append("    \\midrule")
    for _, row in df.iterrows():
        direction = f"{row['train']}\\ensuremath{{\\to}}{row['test']}"
        n_tr = f"{int(row['n_train'])}({int(row['pos_train'])})"
        n_te = f"{int(row['n_test'])}({int(row['pos_test'])})"
        pr = fmt_float(row["full_pr_auc"])
        d1 = fmt_float(row["no_cue1_delta"])
        d2 = fmt_float(row["no_cue2_delta"])
        d3 = fmt_float(row["no_cue3_delta"])
        construction = latex_escape(str(row["construction"]))
        lines.append(f"    {construction} & {direction} & {n_tr} & {n_te} & {pr} & {d1} & {d2} & {d3} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("\\end{table}")
    with open(OUT_SUMMARY_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write_prevalence_tex(prev_df: pd.DataFrame) -> None:
    # Pivot for compact display
    corpora = ["gum", "ewt", "gumreddit"]
    lines = []
    lines.append("% Auto-generated by python/22_summarize_construction_battery.py")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\caption{Construction battery prevalence by corpus. Values are candidates (positives).}")
    lines.append("  \\label{tab:cx-battery-prevalence}")
    lines.append("  \\begin{tabular}{l r r r}")
    lines.append("    \\toprule")
    lines.append("    Construction & GUM & EWT & GUMReddit \\\\")
    lines.append("    \\midrule")
    for construction in sorted(prev_df["construction"].unique()):
        row_parts = []
        for corpus in corpora:
            sub = prev_df[(prev_df["construction"] == construction) & (prev_df["corpus"] == corpus)]
            if sub.empty:
                row_parts.append("--")
            else:
                n = int(sub["n_candidates"].iloc[0])
                p = int(sub["n_positive"].iloc[0])
                row_parts.append(f"{n}({p})")
        construction_tex = latex_escape(str(construction))
        lines.append(f"    {construction_tex} & {row_parts[0]} & {row_parts[1]} & {row_parts[2]} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("\\end{table}")
    with open(OUT_PREV_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> None:
    if not os.path.exists(EVAL_PATH):
        raise FileNotFoundError(EVAL_PATH)
    if not os.path.exists(PREV_PATH):
        raise FileNotFoundError(PREV_PATH)
    eval_df = pd.read_csv(EVAL_PATH)
    prev_df = pd.read_csv(PREV_PATH)
    summary = make_summary(eval_df)
    summary.to_csv(OUT_SUMMARY, index=False)
    write_summary_tex(summary)
    write_prevalence_tex(prev_df)
    print(f"Wrote {OUT_SUMMARY}, {OUT_SUMMARY_TEX}, {OUT_PREV_TEX}")


if __name__ == "__main__":
    main()
